# Generated by Django 5.2.17 on 2026-08-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('issue_type', models.CharField(choices=[('technical', 'Technical Issue'), ('billing', 'Billing & Payment'), ('account', 'Account Access'), ('other', 'Other Queries')], default='technical', max_length=20)),
                ('issue_detail', models.TextField()),
            ],
        ),
    ]
