# Generated by Django 5.2.17 on 2026-08-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sequences/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='issue_type',
            field=models.CharField(choices=[('dna', 'DNA Analysis'), ('visualisation', 'Graph Generation'), ('account', 'Account Access'), ('other', 'Other Queries')], default='technical', max_length=20),
        ),
    ]
